docs/.vitepress/config.ts
docs/guide/button/button.md
docs/guide/button/examples/ButtonDisabledExample.vue
docs/guide/button/examples/ButtonIconExample.vue
docs/guide/button/examples/ButtonLoadingExample.vue
docs/guide/button/examples/ButtonPrefixExample.vue
docs/guide/button/examples/ButtonSquareExample.vue
docs/guide/buttonGroup/buttonGroup.md
docs/guide/buttonGroup/examples/ButtonGroupBasicExample.vue
docs/guide/buttonGroup/examples/ButtonGroupIconExample.vue
docs/guide/spinner/examples/SpinnerBasicExample.vue
docs/guide/spinner/examples/SpinnerColorExample.vue
docs/guide/spinner/examples/SpinnerSizeExample.vue
docs/guide/spinner/spinner.md
package-lock.json
package.json
src/components/Button/Button.vue
src/components/Button/tests/Button.spec.ts
src/components/Button/useButtonClasses.ts
src/components/Button/useButtonSpinner.ts
src/components/ButtonGroup/ButtonGroup.vue
src/components/Spinner/Spinner.vue
src/components/Spinner/useSpinnerClasses.ts
src/composables/useColor.ts
src/index.ts
vitest.config.ts

feat: button, button-group, spinner

---

package-lock.json
src/components/Dropdown/Dropdown.css
src/components/Dropdown/Dropdown.vue

Add parent div on slot to allow custom trigger on Dropdown and transition prop + element to Dropdown content

Custom Trigger + Transition ( Dropdown )

---

CONTRIBUTING.md

Made a quick update to the Contributing page to link to some Vue courses instead of the leftover React courses that were linked.

Quick update to Contributing page

---

docs/.vitepress/config.ts
docs/components/avatar/avatar.md
docs/components/avatar/examples/AvatarAlternativeTextExample.vue
docs/components/avatar/examples/AvatarBorderedExample.vue
docs/components/avatar/examples/AvatarDotIndicatorExample.vue
docs/components/avatar/examples/AvatarDotIndicatorPositionExample.vue
docs/components/avatar/examples/AvatarExample.vue
docs/components/avatar/examples/AvatarPlaceholderExample.vue
docs/components/avatar/examples/AvatarPlaceholderInitialsExample.vue
docs/components/avatar/examples/AvatarSizeExample.vue
docs/components/avatar/examples/StackedAvatarsExample.vue
src/components/Avatar/Avatar.vue
src/components/Avatar/StackedAvatars.vue
src/components/Avatar/StackedAvatarsCounter.vue
src/components/Avatar/composables/useAvatarClasses.ts
src/components/Avatar/types.ts
src/index.ts

Issue #51 
Preview: https://flowbite-vue-git-avatar-component-cogor.vercel.app/components/avatar/avatar.html

Added an avatar component (Issue #51)

---

docs/.vitepress/config.ts
docs/components/badge/badge.md
docs/components/badge/examples/BadgeExample.vue
docs/components/badge/examples/BadgeIconsExample.vue
docs/components/badge/examples/BadgeLinksExample.vue
docs/components/badge/examples/BadgeOnlyIconsExample.vue
docs/components/badge/examples/BadgeSizesExample.vue
docs/components/badge/examples/BadgeTypesExample.vue
src/components/Badge/Badge.vue
src/components/Badge/composables/useBadgeClasses.ts
src/components/Badge/types.ts

Added a badge component (Issue #52)

---

docs/.vitepress/config.ts
docs/components/modal/examples/ModalExample.vue
docs/components/modal/examples/ModalSizeExample.vue
docs/components/modal/modal.md
src/components/Modal/Modal.vue
src/components/Modal/types.ts

Adds a basic version of the modal component. This component will still need additional updates to align with the functionality of the main Flowbite modal component. This first version implements the functions: 
- show
- hide 
- toggle

Add basic modal component (Issue #56)

---

docs/components/carousel/carousel.md
docs/components/carousel/examples/CarouselAutomaticSlideExample.vue
docs/components/carousel/examples/CarouselDefaultExample.vue
docs/components/carousel/examples/CarouselNoControlsExample.vue
docs/components/carousel/examples/CarouselNoIndicatorsExample.vue
docs/components/carousel/examples/CarouselPicturesExample.vue
docs/components/carousel/examples/CarouselSlideExample.vue
docs/components/carousel/examples/CarouselSlideIntervalExample.vue
src/components/Carousel/Carousel.vue

Add basic carousel component (Issue #55)

---

src/components/Input/Input.vue

Based on: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input
With the help of @warddos

Adds support for all input types.

---

src/components/Navbar/NavbarLink.ts

Resolve a registered component by name.
It allow to use a custom link component like this:
`<NavbarLink linkAttr="to" link="/about" component="RouterLink">About</NavbarLink>`

feat: resolve component link

---

docs/components/tabs.md
src/components/Tabs/Tabs.vue

Added click event on TabPane component that we can hook from Tabs component.

Add @click for TabPane component

---

docs/.vitepress/config.ts
docs/components/accordion.md
docs/components/alert.md
docs/components/avatar.md
docs/components/badge.md
docs/components/breadcrumb.md
docs/components/button-group.md
docs/components/button.md
docs/components/card.md
docs/components/carousel.md
docs/components/checkbox.md
docs/components/dropdown.md
docs/components/footer.md
docs/components/input.md
docs/components/list-group.md
docs/components/modal.md
docs/components/navbar.md
docs/components/pagination.md
docs/components/progress.md
docs/components/rating.md
docs/components/select.md
docs/components/sidebar.md
docs/components/spinner.md
docs/components/table.md
docs/components/tabs.md
docs/components/timeline.md
docs/components/toast.md
docs/components/toggle.md
docs/components/tooltip.md

Hey @cogor,
I've made some really small, but important adjustments for SEO titles.
Cheers,
Zoltan

Seo improvements

---

docs/.vitepress/config.ts
docs/components/range.md
docs/components/range/examples/DefaultRange.vue
docs/components/range/examples/DisabledRange.vue
docs/components/range/examples/MinMaxRange.vue
docs/components/range/examples/SizeRange.vue
docs/components/range/examples/StepsRange.vue
src/components/Range/Range.vue
src/components/Range/composables/useRangeClasses.ts
src/index.ts

- Range slider example
- Disabled state
- Min and max
- Steps
- Sizes

feat(component): New range slider

---

docs/components/input.md
docs/components/input/examples/InputExample.vue
src/components/Input/Input.vue

Update input field props schema similar to other form components and add v-modal to docs.

Update input props schema

---

docs/components/input.md
docs/components/input/examples/InputRequiredExample.vue
src/components/Input/Input.vue

feat(input): Allow to set "required" attribute

---

docs/.vitepress/config.ts
docs/components/textarea.md
docs/components/textarea/examples/CommentTextarea.vue
docs/components/textarea/examples/DefaultTextarea.vue
src/components/Textarea/Textarea.vue
src/components/Textarea/composables/useTextareaClasses.ts
src/index.ts

- Textarea example
- Comment box

feat(component): new textarea component

---

docs/components/input.md
docs/components/input/examples/InputHelperExample.vue
docs/components/input/examples/InputPrefixExample.vue
docs/components/input/examples/InputSizeExample.vue
docs/components/input/examples/InputSuffixExample.vue
docs/components/input/examples/InputValidationExample.vue
src/components/Input/Input.vue
src/components/Input/composables/useInputClasses.ts
src/components/Input/types.ts

Introduce to `Input` component:
- `validationStatus` prop to set validation status (success or error).
- `validationMessage` slot to add validation message.
Also minor fixes for other examples, to supress Vue warning message due to missing `v-model`.

feat(input): Setting validation status and message.

---

docs/components/pagination.md
docs/components/pagination/examples/PaginationExample.vue
docs/components/pagination/examples/PaginationNavigationExample.vue
docs/components/pagination/examples/PaginationSlotsExample.vue
docs/components/pagination/examples/PaginationTableExample.vue
docs/components/pagination/examples/PaginationWithCustomSlice.vue
docs/components/pagination/examples/PaginationWithCustomTextExample.vue
docs/components/pagination/examples/PaginationWithIconsExample.vue
src/components/Pagination/Pagination.vue

Pagination component improvements

---

src/components/FileInput/FileInput.vue

Added "multiple" prop to hidden input in the dropzone.

Fixed dropzone not applying multiple prop (#185)

---

docs/components/button.md
docs/components/button/examples/ButtonLinkExample.vue
src/components/FileInput/FileInput.vue

Updated some code to match the example buttons and the code.

Fixed button docs inconsistencies

---

src/components/Button/Button.vue

This MR solves the problem report in ticket #232
closes #232

fix: add disabled in component when is a button

---

docs/components/button.md
docs/components/range/examples/FwbRangeExample.vue
docs/components/range/examples/FwbRangeExampleDisabled.vue
docs/components/range/examples/FwbRangeExampleMinMax.vue
docs/components/range/examples/FwbRangeExampleSize.vue
docs/components/range/examples/FwbRangeExampleSteps.vue

Hey... I've fixed few issues... and added few to the list here (41-45): https://github.com/themesberg/flowbite-vue/discussions/236
```
41. alert#additional-content could use `fwb-button` instead of HTML one
42. "Carousel with slide animation" slide animation doesn't work
43. we should unify sizes... sometime we have prop `size`with different option.. and sometimes we have dedicated prop like `large` (pagination)
44. `Failed to resolve component: router-link` in Sidebar component (we need to add vue router dependency for that to work)
45. `file upload` component button is too dark in light theme
```
I'm getting an error on Toast provider page (which result in toasts not disappearing): http://localhost:5173/components/toastProvider/toastProvider (screen below) but I'm unable to focus now to …

Fwb rename - few fixes after component review

---

docs/components/pagination/examples/FwbPaginationExampleTable.vue
src/components/FwbPagination/FwbPagination.vue

fix for the https://github.com/themesberg/flowbite-vue/issues/246 issue.

fix-issue-#246-pagination-error

---

docs/pages/getting-started.md

fix for the https://github.com/themesberg/flowbite-vue/issues/269 issue

added missing quickstart step

---

package-lock.json
package.json

version update before the release

chore: release v0.1.7

---

package.json

entry points fixed for type: module
